apiVersion: v1
kind: Service
metadata:
  name: backend-bugatti
  labels:
    app: backend-bugatti
    component: api
    shop: bugatti
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: backend-bugatti

# Made with Bob
