apiVersion: v1
kind: Service
metadata:
  name: frontend-bugatti
  labels:
    app: frontend-bugatti
    component: ui
    shop: bugatti
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: frontend-bugatti

# Made with Bob
